# Human-readable feature names

FEATURE_NAMES = {
    "dur": "Connection duration",
    "sbytes": "Bytes sent",
    "dbytes": "Bytes received",
    "sttl": "Source TTL",
    "dttl": "Destination TTL",
    "sloss": "Packets lost (source)",
    "dloss": "Packets lost (destination)",
    "sload": "Source traffic rate",
    "dload": "Destination traffic rate",
    "spkts": "Packets sent",
    "dpkts": "Packets received",
    "swin": "Source TCP window size",
    "dwin": "Destination TCP window size",
    "stcpb": "Source TCP base seq",
    "dtcpb": "Destination TCP base seq",
    "smeansz": "Average packet size (source)",
    "dmeansz": "Average packet size (destination)",
    "trans_depth": "HTTP transaction depth",
    "res_bdy_len": "Response body size",
    "sjit": "Source jitter",
    "djit": "Destination jitter",
    "sintpkt": "Time between packets (source)",
    "dintpkt": "Time between packets (destination)",
    "tcprtt": "TCP round trip time",
    "synack": "SYN-ACK delay",
    "ackdat": "ACK delay",
    "ct_state_ttl": "Connection state behavior",
    "ct_flw_http_mthd": "HTTP method usage",
    "is_ftp_login": "FTP login detected",
    "ct_ftp_cmd": "FTP command activity",
    "ct_srv_src": "Connections from same source",
    "ct_srv_dst": "Connections to same destination",
    "ct_dst_ltm": "Recent connections to destination",
    "ct_src_ltm": "Recent connections from source",
    "ct_src_dport_ltm": "Source to port activity",
    "ct_dst_sport_ltm": "Destination to source port activity",
    "ct_dst_src_ltm": "Connections between source and destination"
}